title: Vault27
description: Network Engineering Notes
show_downloads: false
markdown: kramdown
highlighter: rouge
show_description: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: false
