title: Vault 27
description: Secure Network Engineering Notes
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

baseurl: ""
url: "https://vault27.github.io"

style: dark
listen_for_clients_preferred_style: false

container_width: 80

markdown: kramdown

sass:
  style: compressed
