title: Vault 27
description: Secure Network Engineering Notes
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme

baseurl: ""
url: "https://vault27.github.io"

style: dark
listen_for_clients_preferred_style: false
